@startuml

class Ingrediente{
    unsignedBigInteger id    
    unsignedBigInteger user_id
    unsignedBigInteger cat_id

    String nombre
    String descripcion
    String marca 
    String barcode
    String imagen
    String url
    .. Info nutricional ..
    Integer calorias                
    Decimal fat_total
    Decimal fat_saturadas
    Decimal fat_poliinsaturadas
    Decimal fat_monoinsaturadas
    Decimal fat_trans
    Decimal colesterol
    Decimal sodio
    Decimal potasio
    Decimal fibra
    Decimal carb_total
    Decimal carb_azucar
    Decimal proteina
    ____
    User user()
    Integer getCalorias()
    CategoriaIngrediente getCategoria()
}

class CategoriaIngrediente{
    String nombre
    String descripcion
    int user_id
    int catParent_id

    User user()
    CategoriaIngrediente categoriaPadre()
    CategoriaIngrediente categoriaRaiz()
}

class Receta{
    String nombre
    String descripcion
    Integer calorias
    CategoriaReceta categoria

    User user()
    Ingrediente ingredientes()
    PasoReceta pasos()
}

class CategoriaReceta{
    String nombre
    String descripcion
    int user_id
    int catParent_id

    User user()
    CategoriaReceta categoriaPadre()
    CategoriaReceta categoriaRaiz()
}

class PasoReceta{
    Integer receta_id
    Integer orden
    String texto
}
@enduml